feat: extractor regex abstraction
tolgee/tolgee-cli pull request #3
Opened 2022-08-05 12:17 UTC by cyyynthia

Provides a way for end users to only specify `RexExp`s and not deal with the actual parsing routine.

Implementation not 100% complete: validation is not yet done, and it might be a good idea to validate the `RegExp`s (or their result) to check if the user didn't put parasite capturing blocks.

2022-08-08 06:11 UTC, JanCizmar requested changes
Great job! 🤪  I just hate large functions, since the reader is unable to read less and has to go through whole function until they can find what were they looking for.

2022-08-08 06:11 UTC, JanCizmar commented on src/commands/extractCommand.ts
> +    debug(`\t\tExtracting references`)
It would be cleaner if this was a separate function called `extractReferences`

2022-08-08 06:11 UTC, JanCizmar commented on src/commands/extractCommand.ts
> +    debug(`\t\tPreparing extraction regexes`)
This can be separate function called `prepareRegexes`

2022-08-08 06:11 UTC, JanCizmar commented on src/commands/extractCommand.ts
> +    for (const regex of regexes) {
This can be extracted as `discoverKeys` fn.

2022-08-08 06:11 UTC, JanCizmar commented on src/commands/extractCommand.ts
> +    // perf: deduplicating here is not necessary and would not be worth doing since an additional
OK.

2022-08-08 06:11 UTC, JanCizmar commented on src/commands/extractCommand.ts
> +      debug(`\tExtracting key-like strings`)
This can be extracted as fn `findKeyLikeStrings`

2022-08-08 06:11 UTC, JanCizmar commented on src/commands/extractCommand.ts
> +      debug(`\tLooking for key usage`)
And this can be `findUsages`

2022-08-08 12:02 UTC, cyyynthia commented on src/commands/extractCommand.ts
> +    // xxx: validate user-provided extractor
It should, I haven't gotten around doing that though 😅  Hence the `xxx` marker on that comment

2022-08-10 13:07 UTC, JanCizmar approved these changes

2022-08-10 13:08 UTC, merged