fix #36: allow string integer in config
tolgee/tolgee-cli pull request #37
Opened 2023-03-12 16:22 UTC by ecstrema

I believe this is the simplest way to fix the issue.

This hasn't been tested. I'll test it if you believe it's worth it.

2023-03-13 15:36 UTC, cyyynthia requested changes

2023-03-13 15:36 UTC, cyyynthia commented on src/config/tolgeerc.ts
> +    const id = Number(rc.projectId);
This should be assigned to `cfg`, instead of still assigning the raw value from `rc` to ensure the variable holds the correct expected type.

2023-03-19 15:04 UTC, ecstrema commented on src/config/tolgeerc.ts
> +    if (Number.isNaN(cfg.projectId)) {
![image](https://user-images.githubusercontent.com/35939574/226185175-5acc8efb-6d4f-4ff4-bdb9-cb02fe3970fe.png)

You're right. It seems good for most, though as you can see from above, there are a few edge cases

2023-03-19 16:22 UTC, ecstrema commented on src/config/tolgeerc.ts
> +    if (Number.isNaN(cfg.projectId)) {
Does that seem better?

2023-03-21 09:03 UTC, Martin005 commented on src/config/tolgeerc.ts
> +    if (Number.isNaN(cfg.projectId)) {
Yeah, I know this isn't perfect, but it's definitely better 🙂

2023-03-21 09:08 UTC, Martin005 commented
@ecstrema Please run Prettier on your changes 🙂

2023-03-28 17:44 UTC, cyyynthia approved these changes
LGTM, can be merged once Prettier has been ran on the files

2023-04-03 09:42 UTC, merged